"""add_date_fin_essai_to_worker

Revision ID: 09676a08809a
Revises: d7e0ab50ae93
Create Date: 2025-12-24 22:05:43.396280

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '09676a08809a'
down_revision: Union[str, Sequence[str], None] = 'd7e0ab50ae93'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
