"""add_contribution_fields_to_employer

Revision ID: 623602fbeca1
Revises: 
Create Date: 2025-11-20 10:00:01.247758

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '623602fbeca1'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Ajouter les colonnes manquantes à la table employers
    op.add_column('employers', sa.Column('taux_sal_cnaps', sa.Float(), server_default='1.0', nullable=True))
    op.add_column('employers', sa.Column('plafond_cnaps_base', sa.Float(), server_default='0.0', nullable=True))
    op.add_column('employers', sa.Column('taux_pat_fmfp', sa.Float(), server_default='1.0', nullable=True))
    op.add_column('employers', sa.Column('taux_sal_smie', sa.Float(), server_default='0.0', nullable=True))
    op.add_column('employers', sa.Column('smie_forfait_sal', sa.Float(), server_default='0.0', nullable=True))
    op.add_column('employers', sa.Column('smie_forfait_pat', sa.Float(), server_default='0.0', nullable=True))
    
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('employers', 'smie_forfait_pat')
    op.drop_column('employers', 'smie_forfait_sal')
    op.drop_column('employers', 'taux_sal_smie')
    op.drop_column('employers', 'taux_pat_fmfp')
    op.drop_column('employers', 'plafond_cnaps_base')
    op.drop_column('employers', 'taux_sal_cnaps')
    # ### end Alembic commands ###
