from typing import Dict


CANONICAL_ROLE_BINDINGS = [
    ("admin", "Administrateur Systeme", "global", "admin"),
    ("rh", "Ressources Humaines", "global_or_company", "rh"),
    ("employeur", "Direction Employeur", "company", "employeur"),
    ("direction", "Direction", "company", "direction"),
    ("departement", "Responsable Departement", "organizational_unit", "departement"),
    ("manager", "Manager", "organizational_unit", "manager"),
    ("employe", "Salarie", "self", "employe"),
    ("comptable", "Comptable", "company", "comptable"),
    ("juridique", "Juridique", "company", "juridique"),
    ("inspecteur", "Inspection", "assigned_case_or_company", "inspecteur"),
    ("audit", "Audit", "global_or_company", "audit"),
    ("recrutement", "Recrutement", "company", "recrutement"),
]

ENTERPRISE_ROLE_BINDINGS = [
    ("system_admin", "System Admin", "global", "admin"),
    ("employer_admin", "Employer Admin", "company", "employeur"),
    ("hr_manager", "HR Manager", "company", "rh"),
    ("hr_officer", "HR Officer", "company", "rh"),
    ("employee", "Employee", "self", "employe"),
    ("labor_inspector", "Labor Inspector", "assigned_case_or_company", "inspecteur"),
    ("labor_inspector_supervisor", "Labor Inspector Supervisor", "assigned_case_or_company", "inspecteur"),
    ("staff_delegate", "Staff Delegate", "company", "employe"),
    ("works_council_member", "Works Council Member", "company", "employe"),
    ("judge_readonly", "Judge Readonly", "read_only_external", "judge_readonly"),
    ("court_clerk_readonly", "Court Clerk Readonly", "read_only_external", "court_clerk_readonly"),
    ("intra_user", "INTRA User", "company", "direction"),
    ("auditor_readonly", "Auditor Readonly", "global_or_company", "audit"),
    ("super_administrateur_systeme", "Super Administrateur Systeme", "global", "admin"),
    ("administrateur_technique", "Administrateur Technique", "global", "admin"),
    ("administrateur_fonctionnel_rh", "Administrateur Fonctionnel RH", "global_or_company", "rh"),
    ("administrateur_securite_iam_habilitations", "Administrateur Securite / IAM", "global", "admin"),
    ("auditeur_controle_interne_conformite", "Auditeur / Controle Interne", "global_or_company", "audit"),
    ("dg_direction_generale", "Direction Generale", "company", "direction"),
    ("direction_executive_dga", "Direction Executive", "company", "direction"),
    ("drh", "Directeur des Ressources Humaines", "global_or_company", "rh"),
    ("responsable_rh_gestionnaire_rh", "Responsable RH", "company", "rh"),
    ("assistante_rh", "Assistante RH", "company", "rh"),
    ("directeur_administratif", "Directeur Administratif", "company", "direction"),
    ("daf", "Directeur Administratif et Financier", "company", "comptable"),
    ("comptable_finance", "Comptable / Finance", "company", "comptable"),
    ("controleur_gestion_sociale", "Controleur de Gestion Sociale", "company", "audit"),
    ("gestionnaire_paie", "Gestionnaire Paie", "company", "comptable"),
    ("responsable_paie_valideur_paie", "Responsable Paie / Valideur", "company", "comptable"),
    ("responsable_declarations_sociales_fiscales", "Responsable Declarations", "company", "comptable"),
    ("tresorier_gestionnaire_paiement", "Tresorier", "company", "comptable"),
    ("directeur_departement_chef_service_manager_hierarchique", "Directeur Departement / Manager", "organizational_unit", "departement"),
    ("validateur_n1", "Validateur N+1", "organizational_unit", "manager"),
    ("validateur_n2", "Validateur N+2", "organizational_unit", "departement"),
    ("responsable_recrutement", "Responsable Recrutement", "company", "recrutement"),
    ("recruteur_charge_recrutement", "Charge de Recrutement", "company", "recrutement"),
    ("interviewer_evaluateur_technique", "Interviewer / Evaluateur", "company", "recrutement"),
    ("responsable_onboarding_integration", "Responsable Onboarding", "company", "rh"),
    ("responsable_mobilite_interne_carriere", "Responsable Mobilite", "company", "rh"),
    ("responsable_performance_gpec_carriere", "Responsable Performance / GPEC", "company", "rh"),
    ("responsable_formation", "Responsable Formation", "company", "rh"),
    ("formateur_interne", "Formateur Interne", "company", "rh"),
    ("responsable_discipline_contentieux_social", "Responsable Discipline / Contentieux", "company", "juridique"),
    ("juriste_rh_juridique_social", "Juriste RH", "company", "juridique"),
    ("responsable_sante_travail", "Responsable Sante Travail", "company", "rh"),
    ("medecine_travail_smie_ostie", "Medecine du Travail", "company", "rh"),
    ("responsable_temps_activites_gta", "Responsable Temps et Activites", "company", "rh"),
    ("gestionnaire_conges_absences", "Gestionnaire Conges / Absences", "company", "rh"),
    ("responsable_organigramme_postes_effectifs", "Responsable Organigramme", "company", "rh"),
    ("responsable_documents_rh_ged_rh", "Responsable Documents RH", "company", "rh"),
    ("candidat", "Candidat", "self", "employe"),
    ("salarie_agent", "Salarie / Agent", "self", "employe"),
    ("salarie_periode_essai", "Salarie en periode d'essai", "self", "employe"),
    ("ancien_salarie", "Ancien Salarie", "self", "employe"),
    ("interimaire", "Interimaire", "self", "employe"),
    ("travailleur_journalier", "Travailleur Journalier", "self", "employe"),
    ("travailleur_saisonnier", "Travailleur Saisonnier", "self", "employe"),
    ("travailleur_temps_partiel", "Travailleur Temps Partiel", "self", "employe"),
    ("travailleur_porte", "Travailleur Porte", "self", "employe"),
    ("entreprise_cliente_portage_salarial", "Entreprise Cliente Portage", "client", "employeur"),
    ("referent_client_manager_client", "Referent Client", "client", "manager"),
    ("comptable_client", "Comptable Client", "client", "comptable"),
    ("responsable_rh_client_portage_salarial", "Responsable RH Client", "client", "rh"),
    ("inspection_travail_controle_externe", "Inspection du Travail Externe", "assigned_case_or_company", "inspecteur"),
    ("commissaire_comptes_auditeur_externe", "Commissaire aux Comptes", "company", "audit"),
    ("consultant_externe_rh_acces_temporaire", "Consultant Externe RH", "company", "rh"),
    ("partenaire_cabinet_prestataire_rh", "Partenaire RH", "company", "rh"),
    ("proprietaire_tenant_acheteur_logiciel", "Proprietaire Tenant", "global", "admin"),
    ("administrateur_tenant_client", "Administrateur Tenant Client", "global_or_company", "admin"),
    ("responsable_multi_societes_groupe", "Responsable Multi-Societes", "group", "direction"),
    ("responsable_etablissement_site", "Responsable Etablissement", "site", "departement"),
    ("responsable_centre_couts_entite_analytique", "Responsable Centre de Couts", "company", "direction"),
    ("responsable_validation_contrats", "Responsable Validation Contrats", "company", "juridique"),
    ("responsable_validation_promotions_affectations_mouvements", "Responsable Validation Mouvements", "company", "rh"),
    ("responsable_acces_delegations", "Responsable Acces et Delegations", "company", "admin"),
    ("utilisateur_lecture_seule_direction", "Utilisateur Lecture Seule Direction", "company", "direction"),
    ("support_client_interne_acces_borne_tracable", "Support Client Interne", "company", "audit"),
    ("pdg", "Direction Generale (Consultatif)", "read_only_global", "direction"),
    ("dg", "Direction Generale (Consultatif)", "read_only_global", "direction"),
    ("agent", "Agent / Salarie", "self", "employe"),
    ("paie", "Gestionnaire Paie", "company", "comptable"),
    ("inspection_travail", "Inspection du Travail", "assigned_case_or_company", "inspecteur"),
]


def build_enterprise_role_definitions() -> Dict[str, Dict[str, str]]:
    rows: Dict[str, Dict[str, str]] = {}
    for code, label, scope, base_role_code in [*CANONICAL_ROLE_BINDINGS, *ENTERPRISE_ROLE_BINDINGS]:
        rows[code] = {
            "label": label,
            "scope": scope,
            "base_role_code": base_role_code,
        }
    return rows
